### ISSUE TITLE
Some way to control this without a IR remote

### ISSUE THREAD

**Issue by VedantParanjape** [rossumur/espflix#7]
I didn't have access to a IR remote. So, I had to spend lot of time understanding the work flow, and then just hardcoded to play in the event loop.

It would be great to have ability to control using serial monitor ;)

**Comment by Elekronixx** [comment]
Can you publish your changes for the loop ?

**Comment by VedantParanjape** [comment]
I don't have the code lying around anymore, sorry. @Elekronixx
